config/routes.rb
Rails.application.routes.draw do
  root    'todos#index'
  get     '/signup', to: 'users#new'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  resources :users
  resources :todos
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :teams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 30 }
  validates :content, presence: true, length: { maximum: 140 }
  validates :by_time, presence: true, length: { maximum: 30 }
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :logged_in_user
    before_action :correct_user,   only: [:edit, :update]

    def index
        @todos = current_user.todos.paginate(page: params[:page], per_page: 5)
    end

    def show
        @todo = current_user.todos.find(params[:id])
    end

    def new
        @todo = current_user.todos.build
    end

    def create
        @todo = current_user.todos.build(todo_params)
        if @todo.save
            flash[:success] = "TODO追加成功"
            redirect_to todos_path
        else
            render 'new'
        end
    end

    def edit
        @todo = current_user.todos.find(params[:id])
    end

    def update
        @todo = current_user.todos.find(params[:id])
        if @todo.update_attributes(todo_params)
            flash[:success] = "更新成功"
            redirect_to todos_path
        else
            render 'edit'
        end
    end

    def destroy
        @todo.destroy
        flash[:success] = "削除成功"
        redirect_to todos_path
    end

    private
        def todo_params
            params.require(:todo).permit(:title, :content, :by_time)
        end

        def correct_user
            @todo = current_user.todos.find_by(id: params[:id])
            redirect_to todo_path if @todo.nil?
        end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>

    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>

    <%= f.label :by_time %>
    <%= f.text_field :by_time, class: 'form-control' %>
      
    <%= f.submit yield(:submit_text), class: "btn btn-lg btn-primary btn-block mt-3" %>
<% end %>

app/views/todos/_todo.html.erb
<div>
    <li><%= link_to todo.title, todo_path(todo.id) %> <%= link_to '編集', edit_todo_path(todo.id) %> <%= link_to '削除', todo, method: :delete, data: { confirm: "本当に削除しますか?" } %></li>
    <li><%= time_ago_in_words(todo.created_at) %>前</li>
</div>

app/views/todos/edit.html.erb
<% provide(:title, 'TODO編集') %>
<% provide(:submit_text, '編集') %>
<h1>TODO編集</h1>
<%= render 'form' %>

app/views/todos/index.html.erb
<% provide(:title, 'TODO一覧') %>
<h1>TODO一覧</h1>
<%= render @todos %>
<%= will_paginate %>
<%= link_to 'TODO追加', new_todo_path %>

app/views/todos/new.html.erb
<% provide(:title, 'TODO追加') %>
<% provide(:submit_text, '追加') %>
<div class="col-sm-4 mx-auto mt-5">
    <h1>TODO追加</h1>
    <%= render 'form' %>
</div>

app/views/todos/show.html.erb
<div>
    <h2>「<%= @todo.title %>」 詳細 </h2>
    <li><%= @todo.content %> </li>
    <li><%= @todo.by_time %> </li>
    <%= link_to '編集', edit_todo_path(@todo.id) %> <%= link_to '削除', @todo, method: :delete, data: { confirm: "本当に削除しますか?" } %>
</div>