config/routes.rb
Rails.application.routes.draw do
  root    'todos#index'
  get     '/signup', to: 'users#new'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  resources :users
  resources :todos
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :teams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm sticky-top navbar-dark bg-dark mb-3">
    <button class="navbar-toggler" type="button" data-toggle="collopse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to "Home", root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse justify-content-end">
        <ul class="navbar-nav">
            <% if logged_in? %>
            <li class="nav-item">
                <%= link_to "TODO", todos_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to "チーム", teams_path, class: 'nav-link' %>
            </li>
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                    ユーザ <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><%= link_to "ユーザ一覧", users_path, class: 'dropdown-item' %></li>
                    <li><%= link_to "フォロー", '#', class: 'dropdown-item' %></li>
                    <li><%= link_to "フォロワー", '#', method: :delete, class: 'dropdown-item' %></li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                    Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user, class: 'dropdown-item' %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user), class: 'dropdown-item' %></li>
                    <li><%= link_to "Log out", logout_path, method: :delete, class: 'dropdown-item' %></li>
                </ul>
            </li>
            <% else %>
            <li class="nav-item">
                <%= link_to "Log in", login_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to "Sign up", signup_path, class: 'nav-link' %>
            </li>
            <% end %>        
        </ul>
    </div>

</nav>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODOForTeam <%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>